import {
  BarChart3,
  Calendar,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Download,
  Filter,
  LayoutDashboard,
  Loader2,
  LogOut,
  Menu,
  MessageSquare,
  Pill,
  Plus,
  Settings,
  Stethoscope,
  User,
  Users,
  X,
} from "lucide-react"

export const Icons = {
  barChart: BarChart3,
  calendar: Calendar,
  calendarDays: CalendarDays,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  creditCard: CreditCard,
  download: Download,
  filter: Filter,
  layoutDashboard: LayoutDashboard,
  logOut: LogOut,
  menu: Menu,
  messageSquare: MessageSquare,
  pill: Pill,
  plus: Plus,
  settings: Settings,
  spinner: Loader2,
  stethoscope: Stethoscope,
  user: User,
  users: Users,
  x: X,
}
